export const MEDICAL_OFFICERS_LOADING = 'MEDICAL_OFFICERS_LOADING'
export const MEDICAL_OFFICERS_INFO = 'MEDICAL_OFFICERS_INFO'
export const MEDICAL_OFFICERS_FAILURE = 'MEDICAL_OFFICERS_FAILURE'

export const PATIENTS_LOADING = 'PATIENTS_LOADING'
export const PATIENTS_INFO = 'PATIENTS_INFO'
export const PATIENTS_FAILURE = 'PATIENTS_FAILURE'

export const ROLES_LOADING = 'ROLES_LOADING'
export const ROLES_INFO = 'ROLES_INFO'
export const ROLES_FAILURE = 'ROLES_FAILURE'

export const RECORDS_LOADING = 'RECORDS_LOADING'
export const RECORDS_INFO = 'RECORDS_INFO'
export const RECORDS_FAILURE = 'RECORDS_FAILURE'
